"""initial_schema

Revision ID: 4a46e36ba048
Revises: 
Create Date: 2026-08-11 19:21:18.511216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a46e36ba048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('old_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=30), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_audit_log_student_id'), 'balance_audit_log', ['student_id'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_parents_telegram_id'), 'parents', ['telegram_id'], unique=True)
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutors_telegram_id'), 'tutors', ['telegram_id'], unique=True)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_tutor_id'), 'message_templates', ['tutor_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_table('tutor_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('charge_on_absent', sa.Boolean(), nullable=False),
    sa.Column('absent_grace_period_hours', sa.Integer(), nullable=False),
    sa.Column('late_cancel_fee_percent', sa.Integer(), nullable=False),
    sa.Column('allow_debt', sa.Boolean(), nullable=False),
    sa.Column('max_debt_amount', sa.Float(), nullable=True),
    sa.Column('debt_reminder_days', sa.JSON(), nullable=False),
    sa.Column('remind_before_hours', sa.JSON(), nullable=False),
    sa.Column('send_homework_to_parent', sa.Boolean(), nullable=False),
    sa.Column('default_lesson_duration', sa.Integer(), nullable=False),
    sa.Column('buffer_between_lessons_min', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('remaining_lessons', sa.Integer(), nullable=False),
    sa.Column('price_per_lesson', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_student_id'), 'packages', ['student_id'], unique=False)
    op.create_index(op.f('ix_packages_tutor_id'), 'packages', ['tutor_id'], unique=False)
    op.create_table('schedule_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_rules_student_id'), 'schedule_rules', ['student_id'], unique=False)
    op.create_index(op.f('ix_schedule_rules_tutor_id'), 'schedule_rules', ['tutor_id'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exceptions_rule_id'), 'schedule_exceptions', ['rule_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('schedule_rule_id', sa.Integer(), nullable=True),
    sa.Column('exception_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('homework_text', sa.String(length=1000), nullable=True),
    sa.Column('tutor_notes', sa.String(length=1000), nullable=True),
    sa.Column('materials_url', sa.String(length=500), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['schedule_exceptions.id'], ),
    sa.ForeignKeyConstraint(['schedule_rule_id'], ['schedule_rules.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_start_at'), 'lessons', ['start_at'], unique=False)
    op.create_index(op.f('ix_lessons_tutor_id'), 'lessons', ['tutor_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('PACKAGE_PAYMENT', 'LESSON_DEBIT', 'SINGLE_PAYMENT', 'DEBT_PAYMENT', 'ADJUSTMENT', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_student_id'), 'transactions', ['student_id'], unique=False)
    op.create_table('lesson_students',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('homework_done', sa.Boolean(), nullable=False),
    sa.Column('price_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'student_id')
    )

    # === Performance indexes ===
    op.create_index("idx_transactions_student_created", "transactions", ["student_id", "created_at"])
    op.create_index("idx_schedule_rules_tutor_active", "schedule_rules", ["tutor_id", "is_active", "effective_from", "effective_to"])
    op.create_index("idx_schedule_exceptions_rule_date", "schedule_exceptions", ["rule_id", "date"])
    op.create_index("idx_lessons_start_status", "lessons", ["start_at", "status"])
    op.create_index("idx_lesson_students_student", "lesson_students", ["student_id", "status"])
    op.create_index("idx_balance_audit_student", "balance_audit_log", ["student_id", "created_at"])
    op.create_index("idx_message_templates_tutor_type", "message_templates", ["tutor_id", "type"])


def downgrade() -> None:
    # Drop custom performance indexes first
    op.drop_index("idx_message_templates_tutor_type", table_name="message_templates")
    op.drop_index("idx_balance_audit_student", table_name="balance_audit_log")
    op.drop_index("idx_lesson_students_student", table_name="lesson_students")
    op.drop_index("idx_lessons_start_status", table_name="lessons")
    op.drop_index("idx_schedule_exceptions_rule_date", table_name="schedule_exceptions")
    op.drop_index("idx_schedule_rules_tutor_active", table_name="schedule_rules")
    op.drop_index("idx_transactions_student_created", table_name="transactions")

    # Then drop tables and autogenerated indexes
    op.drop_table('lesson_students')
    op.drop_index(op.f('ix_transactions_student_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_lessons_tutor_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_start_at'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_schedule_exceptions_rule_id'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index(op.f('ix_schedule_rules_tutor_id'), table_name='schedule_rules')
    op.drop_index(op.f('ix_schedule_rules_student_id'), table_name='schedule_rules')
    op.drop_table('schedule_rules')
    op.drop_index(op.f('ix_packages_tutor_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_student_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('tutor_settings')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_message_templates_tutor_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_tutors_telegram_id'), table_name='tutors')
    op.drop_table('tutors')
    op.drop_index(op.f('ix_parents_telegram_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_balance_audit_log_student_id'), table_name='balance_audit_log')
    op.drop_table('balance_audit_log')