"""fix_is_paid_default

Revision ID: 552a7a50fb62
Revises: 4043ee3506d5
Create Date: 2026-08-18 09:48:53.561639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552a7a50fb62'
down_revision: Union[str, None] = '4043ee3506d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
