"""add_student_invite_codes

Revision ID: bc6e51d7ed91
Revises: b850430a6bec
Create Date: 2026-08-16 10:46:59.835301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6e51d7ed91'
down_revision: Union[str, None] = 'b850430a6bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_invite_codes_code'), 'student_invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_student_invite_codes_student_id'), 'student_invite_codes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_invite_codes_student_id'), table_name='student_invite_codes')
    op.drop_index(op.f('ix_student_invite_codes_code'), table_name='student_invite_codes')
    op.drop_table('student_invite_codes')
    # ### end Alembic commands ###
