"""add_student_is_active

Revision ID: c875aa1c4b5a
Revises: b450bee334c5
Create Date: 2026-08-13 11:34:22.974850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c875aa1c4b5a'
down_revision: Union[str, None] = 'b450bee334c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_balance_audit_student')

    with op.batch_alter_table('lesson_students', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_students_student')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('idx_lessons_start_status')

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_message_templates_tutor_type')

    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_exceptions_rule_date')

    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_rules_tutor_active')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_student_created')

    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_student_created', ['student_id', 'created_at'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_rules_tutor_active', ['tutor_id', 'is_active', 'effective_from', 'effective_to'], unique=False)

    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_exceptions_rule_date', ['rule_id', 'date'], unique=False)

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index('idx_message_templates_tutor_type', ['tutor_id', 'type'], unique=False)

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index('idx_lessons_start_status', ['start_at', 'status'], unique=False)

    with op.batch_alter_table('lesson_students', schema=None) as batch_op:
        batch_op.create_index('idx_lesson_students_student', ['student_id', 'status'], unique=False)

    with op.batch_alter_table('balance_audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_balance_audit_student', ['student_id', 'created_at'], unique=False)

    # ### end Alembic commands ###
