"""sync_schema

Revision ID: d3128a9a4668
Revises: 552a7a50fb62
Create Date: 2026-08-18 17:51:53.231342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3128a9a4668'
down_revision: Union[str, None] = '552a7a50fb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('old_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=30), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_audit_log_student_id'), 'balance_audit_log', ['student_id'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_parents_telegram_id'), 'parents', ['telegram_id'], unique=True)
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tutors_telegram_id'), 'tutors', ['telegram_id'], unique=True)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_tutor_id'), 'message_templates', ['tutor_id'], unique=False)
    op.create_table('schedule_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_rules_tutor_id'), 'schedule_rules', ['tutor_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), server_default='25.00', nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_table('tutor_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('charge_on_absent', sa.Boolean(), nullable=False),
    sa.Column('absent_grace_period_hours', sa.Integer(), nullable=False),
    sa.Column('late_cancel_fee_percent', sa.Integer(), nullable=False),
    sa.Column('allow_debt', sa.Boolean(), nullable=False),
    sa.Column('max_debt_amount', sa.Float(), nullable=True),
    sa.Column('debt_reminder_days', sa.JSON(), nullable=False),
    sa.Column('remind_before_hours', sa.JSON(), nullable=False),
    sa.Column('send_homework_to_parent', sa.Boolean(), nullable=False),
    sa.Column('default_lesson_duration', sa.Integer(), nullable=False),
    sa.Column('buffer_between_lessons_min', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('remaining_lessons', sa.Integer(), nullable=False),
    sa.Column('price_per_lesson', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_student_id'), 'packages', ['student_id'], unique=False)
    op.create_index(op.f('ix_packages_tutor_id'), 'packages', ['tutor_id'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exceptions_rule_id'), 'schedule_exceptions', ['rule_id'], unique=False)
    op.create_table('schedule_rule_students',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'student_id')
    )
    op.create_table('student_invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_invite_codes_code'), 'student_invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_student_invite_codes_student_id'), 'student_invite_codes', ['student_id'], unique=False)
    op.create_table('student_subjects',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('price_per_lesson', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'subject')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('schedule_rule_id', sa.Integer(), nullable=True),
    sa.Column('exception_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('homework_text', sa.String(length=1000), nullable=True),
    sa.Column('tutor_notes', sa.String(length=1000), nullable=True),
    sa.Column('materials_url', sa.String(length=500), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['schedule_exceptions.id'], ),
    sa.ForeignKeyConstraint(['schedule_rule_id'], ['schedule_rules.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_start_at'), 'lessons', ['start_at'], unique=False)
    op.create_index(op.f('ix_lessons_tutor_id'), 'lessons', ['tutor_id'], unique=False)
    op.create_table('cancellation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('tutor_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['tutors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellation_requests_lesson_id'), 'cancellation_requests', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_student_id'), 'cancellation_requests', ['student_id'], unique=False)
    op.create_table('homework_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_attachments_lesson_id'), 'homework_attachments', ['lesson_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('PACKAGE_PAYMENT', 'LESSON_DEBIT', 'LESSON_REFUND', 'MANUAL_ADJUSTMENT', 'MANUAL_DEDUCTION', name='transactiontype'), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_student_id'), 'transactions', ['student_id'], unique=False)
    op.create_table('lesson_students',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('homework_done', sa.Boolean(), nullable=False),
    sa.Column('price_charged', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_students')
    op.drop_index(op.f('ix_transactions_student_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_homework_attachments_lesson_id'), table_name='homework_attachments')
    op.drop_table('homework_attachments')
    op.drop_index(op.f('ix_cancellation_requests_student_id'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_lesson_id'), table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_index(op.f('ix_lessons_tutor_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_start_at'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('student_subjects')
    op.drop_index(op.f('ix_student_invite_codes_student_id'), table_name='student_invite_codes')
    op.drop_index(op.f('ix_student_invite_codes_code'), table_name='student_invite_codes')
    op.drop_table('student_invite_codes')
    op.drop_table('schedule_rule_students')
    op.drop_index(op.f('ix_schedule_exceptions_rule_id'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index(op.f('ix_packages_tutor_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_student_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('tutor_settings')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_schedule_rules_tutor_id'), table_name='schedule_rules')
    op.drop_table('schedule_rules')
    op.drop_index(op.f('ix_message_templates_tutor_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_tutors_telegram_id'), table_name='tutors')
    op.drop_table('tutors')
    op.drop_index(op.f('ix_parents_telegram_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_balance_audit_log_student_id'), table_name='balance_audit_log')
    op.drop_table('balance_audit_log')
    # ### end Alembic commands ###
