"""add_student_subjects_table

Revision ID: db042377553c
Revises: c875aa1c4b5a
Create Date: 2026-08-13 11:47:01.563665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db042377553c'
down_revision: Union[str, None] = 'c875aa1c4b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'student_subjects',
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('student_id', 'subject'),
    )


def downgrade() -> None:
    op.drop_table('student_subjects')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
