"""add landing and currency fields

Revision ID: f1afbd584d5a
Revises: 552a7a50fb62
Create Date: 2026-08-19 09:05:02.000548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1afbd584d5a'
down_revision: Union[str, None] = '552a7a50fb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('tutors', sa.Column('slug', sa.String(length=30), nullable=True))
    op.add_column('tutors', sa.Column('landing_headline', sa.String(length=200), nullable=True))
    op.add_column('tutors', sa.Column('landing_bio', sa.Text(), nullable=True))
    op.add_column('tutors', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('tutors', sa.Column('landing_theme', sa.String(length=20), nullable=False))
    op.add_column('tutors', sa.Column('is_landing_published', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tutors_slug'), 'tutors', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutors_slug'), table_name='tutors')
    op.drop_column('tutors', 'is_landing_published')
    op.drop_column('tutors', 'landing_theme')
    op.drop_column('tutors', 'photo_url')
    op.drop_column('tutors', 'landing_bio')
    op.drop_column('tutors', 'landing_headline')
    op.drop_column('tutors', 'slug')
    op.drop_column('tutors', 'currency')
    # ### end Alembic commands ###
